trigger:
- main
- development

pool: {}

variables:
  dockerRegistryServiceConnection: 'docker-hub-juliocesarmidia'
  imageRepository: 'kube-pod-metrics-collector'

stages:
  - stage: CI
    jobs:
    - job: Install
      strategy:
        matrix:
          Python39:
            python.version: '3.9'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - script: |
          python -m pip install --upgrade pip
          pip install yamllint
          yamllint pod.yaml
        displayName: 'Linter for yaml files'

      - script: |
          docker version
          docker container run --rm \
            --name pylint \
            -v $PWD/src:/usr/src/app \
            -w /usr/src/app \
            --entrypoint "" \
            cytopia/black:latest-0.2 sh -c "black --check -v ."
        displayName: 'Linter for python files'

    - job: Build
      dependsOn: Install
      strategy:
        matrix:
          Python39:
            python.version: '3.9'

      steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: $(dockerRegistryServiceConnection) # string. Container registry.

      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: 'buildAndPush' # 'buildAndPush' | 'build' | 'push' | 'login' | 'logout' | 'start' | 'stop'. Required. Command. Default: buildAndPush.
          Dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile' # string. Required when command = build || command = buildAndPush. Dockerfile. Default: **/Dockerfile.
          buildContext: '$(Build.SourcesDirectory)/src' # string. Optional. Use when command = build || command = buildAndPush. Build context. Default: **.
          repository: '$(imageRepository)' # string. Optional. Use when command != login && command != logout && command != start && command != stop. Container repository.
          tags: |
            $(Build.BuildId)
            latest
          # arguments: # string. Optional. Use when command != login && command != logout && command != buildAndPush. Arguments.
