# apiVersion: v1
# kind: Secret
# metadata:
#   name: pod-metrics-secrets
#   namespace: default
# data:
#   AWS_ACCESS_KEY_ID: ""
#   AWS_SECRET_ACCESS_KEY: ""
#   AWS_DEFAULT_REGION: ""

# ---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-metrics-sa
  namespace: default
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-metrics-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-metrics-binding
roleRef:
  kind: ClusterRole
  name: pod-metrics-role
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: ServiceAccount
  name: pod-metrics-sa
  namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-metrics
  name: pod-metrics
  namespace: default
spec:
  containers:
  - name: pod-metrics
    image: juliocesarmidia/kube-pod-metrics-collector:v1.0.0
    imagePullPolicy: Never
    resources:
      limits:
        memory: 256Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 250m
    envFrom:
    - secretRef:
        name: pod-metrics-secrets
    env:
    - name: RUNNING_IN_KUBERNETES
      value: '1'
    - name: SCHEDULE_SECONDS_INTERVAL
      value: '60'
    - name: PENDING_MINS_TO_BE_CRASHED
      value: '5'
    - name: IGNORE_NAMESPACES
      value: 'kube-public,kube-node-lease'
    - name: SEND_TO_CLOUDWATCH
      value: '1'
    - name: CLOUDWATCH_METRIC_NAME
      value: 'CrashedPods'
    - name: CLOUDWATCH_METRIC_NAMESPACE
      value: 'K8sMetrics'
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: HOST_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
  serviceAccountName: pod-metrics-sa
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/memory-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
  - key: "node.kubernetes.io/pid-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
  - key: "node.kubernetes.io/unschedulable"
    operator: "Exists"
    effect: "NoSchedule"
